### PR TITLE
Updates for quality

### PR DESCRIPTION
**Pull request by nkolban**
Removed an unused variable that served no purpose.
Changed a variable type from char to int that was being used only as an array index
as my compiler doesn't like chars used as indices.

### CODE REVIEW

**Comment by mgrusin** [comment]
Hi Neil, thanks for looking at this code and your debugging. Re. char to int, I hate to waste a byte of SRAM if I don't have to; how about changing it to a uint8_t? (The whole library could frankly use that for better portability).

**Comment by mgrusin** [comment]
Also out of curiosity, what compiler / destination processor are you using?

**Comment by nkolban** [comment]
I'm compiling using xtensa-esp32-elf-gcc which reports as 4.8.5.  The target is for the ESP32.

**Comment by nkolban** [comment]
Changed to uint8_t

**Comment by mgrusin** [comment]
Thanks VERY much Neil, if you ever see anything else that can be improved, please let us know!

**Pull request merged**
